name: build-artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          . /home/runner/.nix-profile/etc/profile.d/nix.sh

      - name: Build
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix --experimental-features 'nix-command flakes' build .#packages.x86_64-linux.default
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: result
